// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxyuuotpbzohlkadunpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4eXV1b3RwYnpvaGxrYWR1bnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTc0MzcsImV4cCI6MjA2OTE3MzQzN30.284IY0CaVLqyaWUQaBHXuM7YFHZCgJfKLOeLVCVNxfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});